//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESignerClient.FileServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileServices.WSFileManagerSoap")]
    public interface WSFileManagerSoap {
        
        // CODEGEN: Generating message contract since element name helloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/helloWorld", ReplyAction="*")]
        ESignerClient.FileServices.helloWorldResponse helloWorld(ESignerClient.FileServices.helloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name documentID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFileBytes", ReplyAction="*")]
        ESignerClient.FileServices.getFileBytesResponse getFileBytes(ESignerClient.FileServices.getFileBytesRequest request);
        
        // CODEGEN: Generating message contract since element name documentID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uploadSignedFile", ReplyAction="*")]
        ESignerClient.FileServices.uploadSignedFileResponse uploadSignedFile(ESignerClient.FileServices.uploadSignedFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ESignerClient.FileServices.helloWorldRequestBody Body;
        
        public helloWorldRequest() {
        }
        
        public helloWorldRequest(ESignerClient.FileServices.helloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class helloWorldRequestBody {
        
        public helloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ESignerClient.FileServices.helloWorldResponseBody Body;
        
        public helloWorldResponse() {
        }
        
        public helloWorldResponse(ESignerClient.FileServices.helloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class helloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string helloWorldResult;
        
        public helloWorldResponseBody() {
        }
        
        public helloWorldResponseBody(string helloWorldResult) {
            this.helloWorldResult = helloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFileBytesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFileBytes", Namespace="http://tempuri.org/", Order=0)]
        public ESignerClient.FileServices.getFileBytesRequestBody Body;
        
        public getFileBytesRequest() {
        }
        
        public getFileBytesRequest(ESignerClient.FileServices.getFileBytesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getFileBytesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string documentID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sessionID;
        
        public getFileBytesRequestBody() {
        }
        
        public getFileBytesRequestBody(string documentID, string sessionID) {
            this.documentID = documentID;
            this.sessionID = sessionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFileBytesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFileBytesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ESignerClient.FileServices.getFileBytesResponseBody Body;
        
        public getFileBytesResponse() {
        }
        
        public getFileBytesResponse(ESignerClient.FileServices.getFileBytesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getFileBytesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] getFileBytesResult;
        
        public getFileBytesResponseBody() {
        }
        
        public getFileBytesResponseBody(byte[] getFileBytesResult) {
            this.getFileBytesResult = getFileBytesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadSignedFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadSignedFile", Namespace="http://tempuri.org/", Order=0)]
        public ESignerClient.FileServices.uploadSignedFileRequestBody Body;
        
        public uploadSignedFileRequest() {
        }
        
        public uploadSignedFileRequest(ESignerClient.FileServices.uploadSignedFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class uploadSignedFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string documentID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] signedFileBytes;
        
        public uploadSignedFileRequestBody() {
        }
        
        public uploadSignedFileRequestBody(string documentID, byte[] signedFileBytes) {
            this.documentID = documentID;
            this.signedFileBytes = signedFileBytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadSignedFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadSignedFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public ESignerClient.FileServices.uploadSignedFileResponseBody Body;
        
        public uploadSignedFileResponse() {
        }
        
        public uploadSignedFileResponse(ESignerClient.FileServices.uploadSignedFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class uploadSignedFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool uploadSignedFileResult;
        
        public uploadSignedFileResponseBody() {
        }
        
        public uploadSignedFileResponseBody(bool uploadSignedFileResult) {
            this.uploadSignedFileResult = uploadSignedFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSFileManagerSoapChannel : ESignerClient.FileServices.WSFileManagerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSFileManagerSoapClient : System.ServiceModel.ClientBase<ESignerClient.FileServices.WSFileManagerSoap>, ESignerClient.FileServices.WSFileManagerSoap {
        
        public WSFileManagerSoapClient() {
        }
        
        public WSFileManagerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSFileManagerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSFileManagerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSFileManagerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESignerClient.FileServices.helloWorldResponse ESignerClient.FileServices.WSFileManagerSoap.helloWorld(ESignerClient.FileServices.helloWorldRequest request) {
            return base.Channel.helloWorld(request);
        }
        
        public string helloWorld() {
            ESignerClient.FileServices.helloWorldRequest inValue = new ESignerClient.FileServices.helloWorldRequest();
            inValue.Body = new ESignerClient.FileServices.helloWorldRequestBody();
            ESignerClient.FileServices.helloWorldResponse retVal = ((ESignerClient.FileServices.WSFileManagerSoap)(this)).helloWorld(inValue);
            return retVal.Body.helloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESignerClient.FileServices.getFileBytesResponse ESignerClient.FileServices.WSFileManagerSoap.getFileBytes(ESignerClient.FileServices.getFileBytesRequest request) {
            return base.Channel.getFileBytes(request);
        }
        
        public byte[] getFileBytes(string documentID, string sessionID) {
            ESignerClient.FileServices.getFileBytesRequest inValue = new ESignerClient.FileServices.getFileBytesRequest();
            inValue.Body = new ESignerClient.FileServices.getFileBytesRequestBody();
            inValue.Body.documentID = documentID;
            inValue.Body.sessionID = sessionID;
            ESignerClient.FileServices.getFileBytesResponse retVal = ((ESignerClient.FileServices.WSFileManagerSoap)(this)).getFileBytes(inValue);
            return retVal.Body.getFileBytesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESignerClient.FileServices.uploadSignedFileResponse ESignerClient.FileServices.WSFileManagerSoap.uploadSignedFile(ESignerClient.FileServices.uploadSignedFileRequest request) {
            return base.Channel.uploadSignedFile(request);
        }
        
        public bool uploadSignedFile(string documentID, byte[] signedFileBytes) {
            ESignerClient.FileServices.uploadSignedFileRequest inValue = new ESignerClient.FileServices.uploadSignedFileRequest();
            inValue.Body = new ESignerClient.FileServices.uploadSignedFileRequestBody();
            inValue.Body.documentID = documentID;
            inValue.Body.signedFileBytes = signedFileBytes;
            ESignerClient.FileServices.uploadSignedFileResponse retVal = ((ESignerClient.FileServices.WSFileManagerSoap)(this)).uploadSignedFile(inValue);
            return retVal.Body.uploadSignedFileResult;
        }
    }
}
