/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esignerclientjava.forms;

import esignerclientjava.beans.SignFileBean;
import esignerclientjava.ws.WSFileManager;
import java.awt.Frame;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author cihan
 */
public class MainForm extends javax.swing.JDialog {

    MainForm mf;
    SignFileBean signFileBean;
    esignerclientjava.ws.WSFileManager wSFileManager;
    esignerclientjava.ws.WSFileManagerSoap fileManagerSoap;

    /**
     * Creates new form MainForm
     */
    public MainForm(java.awt.Frame parent, boolean modal, SignFileBean signFileBean) {
        super(parent, modal);
        initComponents();
        this.signFileBean = signFileBean;
        txtDocumentID.setText(signFileBean.getDocumentId());
        txtFileHash.setText(signFileBean.getFileHash());
        txtFileName.setText(signFileBean.getFileName());
        txtSessionID.setText(signFileBean.getSessionID());
        txtUserName.setText(signFileBean.getUserName());
        wSFileManager = new WSFileManager();
        fileManagerSoap = wSFileManager.getWSFileManagerSoap();
        mf = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDocumentID = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFileName = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtFileHash = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtSessionID = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtUserName = new javax.swing.JTextPane();
        btnShowFile = new javax.swing.JButton();
        btnSignFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("esignerclientjava/forms/messages"); // NOI18N
        setTitle(bundle.getString("mainFormTitle")); // NOI18N

        jLabel1.setText(bundle.getString("documentID")); // NOI18N

        jLabel2.setText(bundle.getString("fileName")); // NOI18N

        jLabel3.setText(bundle.getString("fileHash")); // NOI18N

        jLabel4.setText(bundle.getString("sessionID")); // NOI18N

        jLabel5.setText(bundle.getString("userName")); // NOI18N

        txtDocumentID.setEditable(false);
        txtDocumentID.setName("txtDocumentID"); // NOI18N
        jScrollPane1.setViewportView(txtDocumentID);

        txtFileName.setEditable(false);
        txtFileName.setName("txtFileName"); // NOI18N
        jScrollPane2.setViewportView(txtFileName);

        txtFileHash.setEditable(false);
        txtFileHash.setName("txtFileHash"); // NOI18N
        jScrollPane3.setViewportView(txtFileHash);

        txtSessionID.setEditable(false);
        txtSessionID.setName("txtSessionID"); // NOI18N
        jScrollPane4.setViewportView(txtSessionID);

        txtUserName.setEditable(false);
        txtUserName.setName("txtUserName"); // NOI18N
        jScrollPane5.setViewportView(txtUserName);

        btnShowFile.setText(bundle.getString("showFile")); // NOI18N
        btnShowFile.setName("btnShowFile"); // NOI18N
        btnShowFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowFileMouseClicked(evt);
            }
        });

        btnSignFile.setLabel(bundle.getString("signFile")); // NOI18N
        btnSignFile.setName("btnSignFile"); // NOI18N
        btnSignFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignFileMouseClicked(evt);
            }
        });
        btnSignFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnShowFile, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSignFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShowFile)
                    .addComponent(btnSignFile))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowFileMouseClicked

        byte[] fileBytes = fileManagerSoap.getFileBytes(signFileBean.getDocumentId(), signFileBean.getSessionID());
        Path currentRelativePath = Paths.get("");
        String tempPath = currentRelativePath.toAbsolutePath().toString().concat("\\tmp.pdf");
        try {
            File f = new File(tempPath);
            if (f.exists()) {
                f.delete();
            }
            try (FileOutputStream fileOutputStream = new FileOutputStream(f)) {
                fileOutputStream.write(fileBytes);
            }
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + f);
            //Process p = Runtime.getRuntime().exec(tempPath);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_btnShowFileMouseClicked

    private void btnSignFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignFileMouseClicked


    }//GEN-LAST:event_btnSignFileMouseClicked

    private void btnSignFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignFileActionPerformed
        SignForm dialog = new SignForm(null, true, signFileBean, fileManagerSoap);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnSignFileActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                MainForm dialog = new MainForm(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowFile;
    private javax.swing.JButton btnSignFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane txtDocumentID;
    private javax.swing.JTextPane txtFileHash;
    private javax.swing.JTextPane txtFileName;
    private javax.swing.JTextPane txtSessionID;
    private javax.swing.JTextPane txtUserName;
    // End of variables declaration//GEN-END:variables
}
